name: deploy to server

on: push
  
jobs:
  first_jobs:
    runs-on: ubuntu-latest
    env:
      NAME: var
    steps:
      - name: Hola Mundo
        run : echo "Hola Mundo $var"
  second_jobs:
    needs: first_jobs
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run : echo "Hola Mundo 2 ${{github.ref}}"