name: "test  Accion Deploy"

on:
  push:
    branches: ["main"]
  
jobs:
  deploy-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hacemos pull del codigo"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "publicar version"