name: deploy to server

on: push
  
jobs:
  first_jobs:
    runs-on: ubuntu-latest
    env:
      NAME: var
    steps:
      - name: Hola Mundo
        id: step_1
        run: echo "my_variable=Hola mundo" >> $GITHUB_OUTPUT
        
      - name: obtener mensaje
        run: echo "${{ steps.step_1.outputs.my_variable }}"

  second_jobs:
    needs: first_jobs
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run : echo "Hola Mundo 2 ${{github.ref}}"